trigger:
- master

  pool:
    name: MyAgentPool
    demands:
    - agent.name -equals nuc

  variables:
  - name: COVERITY_TOOL_HOME
    value: /home/siguser/cov-analysis-linux64-2021.06
steps:
- task: synopsys-coverity@1

  # use Coverity plugin for full scans of CI Builds
  inputs:
    coverityService: 'Coverity'
    projectName: 'Insecure Bank'
    streamName: 'insecure-bank'
    checkIssues: true
    issueView: 'build-breakers'
    issueStatus: 'unstable'
    buildCommand: 'mvn -B package -DskipTests'
    customCommandArgs: true
    covBuildArgs: '--fs-capture-search $(Build.SourcesDirectory)'
    covAnalyzeArgs: '--ticker-mode none --strip-path $(Build.SourcesDirectory) --webapp-security'
    covCommitArgs: '--ticker-mode none --description $(Build.BuildURI) --version $(Build.SourceVersion) --scm git'
  displayName: 'Full Scan'
  condition: not(eq(variables['Build.Reason'], 'PullRequest'))

  # use cov-run-desktop for incremental scans of GPRs
- bash: |
    REMOVE="refs/heads/"
    export SYSTEM_PULLREQUEST_TARGETBRANCHNAME="${SYSTEM_PULLREQUEST_TARGETBRANCH//$REMOVE/}"
    export CHANGE_SET=$(git --no-pager diff origin/$SYSTEM_PULLREQUEST_TARGETBRANCHNAME --name-only)
    export STREAM="$(COVERITY_PROJECT)-$SYSTEM_PULLREQUEST_TARGETBRANCHNAME"
    export PATH=$PATH:$COVERITY_TOOL_HOME/bin
    set -x
    cov-run-desktop --dir idir --url $(COV_URL) --stream $STREAM --build mvn -B package -DskipTests
    cov-run-desktop --dir idir --url $(COV_URL) --stream $STREAM --present-in-reference false --ignore-uncapturable-inputs true --exit1-if-defects true $CHANGE_SET
  env:
    COVERITY_PASSPHRASE: $(COVERITY_PASSPHRASE)
    displayName: 'Incremental Scan'
    condition: eq(variables['Build.Reason'], 'PullRequest')